-- ============================================================
-- Project: Credit Risk Portfolio Dashboard
-- Author: Amal S
-- Tool: PostgreSQL
--
-- Description:
-- This SQL query estimates the Risk-Adjusted Return of the
-- loan portfolio by comparing interest income earned with
-- losses generated from loan defaults.
--
-- In lending analytics, risk-adjusted return provides a more
-- realistic measure of portfolio performance because it
-- accounts for the impact of credit risk on profitability.
--
-- The calculation uses the following components:
--
--   • Total Interest Earned
--     Sum of all interest payments received from borrowers.
--
--   • Default Loss
--     Estimated loss calculated as the total loan amount for
--     loans that resulted in default.
--
-- The final metric is calculated using the formula:
--
--     Risk-Adjusted Return =
--     Total Interest Earned − Default Loss
--
-- This metric helps evaluate whether the interest income
-- generated by the portfolio is sufficient to compensate
-- for credit losses resulting from borrower defaults.
--
-- Risk-adjusted return is commonly used in credit portfolio
-- analysis to assess lending performance and determine
-- whether the portfolio is generating adequate returns
-- relative to its risk exposure.
-- ============================================================

---- RISK-ADJUSTED RETURN (Return − Expected Loss) ----

SELECT
    SUM(total_rec_int) -
    SUM(loan_amnt * default_flag) AS risk_adjusted_return

FROM loans_clean;
